name:                glyph
version:             0.1.0.0
github:              "rationalis-petra/glyph"
license:             BSD3
author:              "Connor Redfern"
maintainer:          "connor.redfern@optunset.com.au"
copyright:           "2022 Connor Redfern"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Dependently typed lisp-like language
# category:            Programming Lanugages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rationalis-petra/glyph#readme>

dependencies:
- base >= 4.7 && < 5
- text
- vector
- stm
- lens
- mtl
- containers
- megaparsec
- topograph
- prettyprinter
- prettyprinter-ansi-terminal
- optparse-applicative

ghc-options:
- -Wall
- -Werror
- -Wno-name-shadowing
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions: 
- UndecidableInstances
- TypeFamilies
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- FunctionalDependencies
- OverloadedStrings
- RankNTypes
- TemplateHaskell
- RecordWildCards
- LambdaCase
- GeneralizedNewtypeDeriving
- ConstraintKinds


library:
  source-dirs: src

executables:
  glyph-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glyph

tests:
  glyph-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glyph
