name:                sigil
version:             0.2.0.0
github:              "rationalis-petra/sigil"
license:             BSD3
author:              "Connor Redfern"
maintainer:          "connor.redfern@optunset.com.au"
copyright:           "2022 Connor Redfern"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Dependently typed lisp-like language
# category:            Programming Lanugages

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rationalis-petra/sigil#readme>

dependencies:
- base >= 4.7 && < 5
- text
- text-zipper
- vector
- stm
- lens # TODO: try and replace with microlens
- mtl
- transformers
- pipes
- pipes-parse
- pipes-aeson
- aeson
- directory
- containers
- bytestring
- network
- megaparsec
- topograph
- prettyprinter
- prettyprinter-ansi-terminal
- optparse-applicative
- brick
- vty
- microlens
- microlens-mtl
- microlens-th

ghc-options:
- -Wall
- -Werror
- -Wno-name-shadowing
- -Wno-missing-signatures
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path # to fix build on Windows

default-extensions: 
- ScopedTypeVariables
- UndecidableInstances
- TypeFamilies
- FlexibleInstances
- FlexibleContexts
- MultiParamTypeClasses
- FunctionalDependencies
- OverloadedStrings
- OverloadedLists
- RankNTypes
- TemplateHaskell
- RecordWildCards
- LambdaCase
- GeneralizedNewtypeDeriving
- ConstraintKinds
- PatternSynonyms
- TupleSections
- GADTs
- InstanceSigs


library:
  source-dirs: src

executables:
  sigil:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sigil

tests:
  sigil-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sigil
