# For documentation of this file format, see
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# Resolver to choose a 'specific' stackage snapshot or a compiler version.

resolver: lts-21.11
  #url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/4.yaml

compiler: ghc-9.6.1

# User packages to be built.
packages:
  - .

# Dependency packages to be pulled from upstream that are not in the resolver.
extra-deps: 
  - git: git@github.com:k0001/pipes-aeson.git
    commit: 207696d9c8a15bff8b2dc7f6899575d2b00a8647
  # - pipes-aeson-0.4.1.8
