module Sigil.Concrete () where


{------------------------------- CONCRETE SYNTAX -------------------------------}
{- The concrete syntax module contains two things:                             -}
{- • A set of decorations - types intended to extend a syntax tree             -}
{- • A set of concrete syntax trees                                            -}
{-                                                                             -}
{- Decorations                                                                 -}
{- • Sugar: 'Nice' extra bits like let etc.                                    -}
{- • Implicit: Adds implicit bindings etc.                                     -}
{- • Source: Annotate a syntax tree with source locations                      -}
{-                                                                             -}
{- Concrete Trees                                                              -}
{- • Parsed: Syntax returned by the parser: contains annotated source          -}
{-           locations, but has less stringent type information requirements.  -}
{- • Internal: Generated by type checking: can be consumed by an interpreter   -}
{-             backend.                                                        -}
{-------------------------------------------------------------------------------}
